/**
 * Copies the engine source into `supabase/functions/_shared/engine` so Deno can
 * bundle it with the Edge Functions.
 *
 * Two reasons this is a copy rather than an import:
 *  - `supabase functions deploy` only uploads what lives under the functions
 *    directory, so a relative import reaching out of it would not deploy.
 *  - the engine is written with NodeNext-style `.js` specifiers, which Deno does
 *    not resolve to `.ts` files. They are rewritten on the way through.
 *
 * The copy is generated and git-ignored. Run `pnpm sync:engine` after changing
 * the engine, or just use `pnpm deploy:functions`, which does it for you.
 */

import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'packages', 'engine', 'src');
const target = join(root, 'supabase', 'functions', '_shared', 'engine');

const HEADER = `// Generated by scripts/sync-engine.mjs from packages/engine/src.
// Do not edit: run \`pnpm sync:engine\` instead.
`;

/** Rewrites relative '.js' import specifiers to '.ts' for Deno. */
function rewriteSpecifiers(code) {
  return code.replace(/(from\s+['"]\.[^'"]*?)\.js(['"])/g, '$1.ts$2');
}

function shouldCopy(name) {
  if (!name.endsWith('.ts')) return false;
  // Tests stay behind, and the ambient globals clash with Deno's own lib.
  if (name.endsWith('.test.ts') || name.endsWith('.d.ts')) return false;
  return true;
}

async function main() {
  const entries = await readdir(source, { withFileTypes: true });
  const files = entries.filter((entry) => entry.isFile() && shouldCopy(entry.name));

  if (files.length === 0) {
    throw new Error(`No engine sources found in ${source}`);
  }

  await rm(target, { recursive: true, force: true });
  await mkdir(target, { recursive: true });

  for (const file of files) {
    const code = await readFile(join(source, file.name), 'utf8');
    await writeFile(join(target, file.name), HEADER + rewriteSpecifiers(code), 'utf8');
  }

  console.log(`Synced ${files.length} engine files to supabase/functions/_shared/engine`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
